// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/dev/webfx/platform/ast/xml/parser/jflex/XmlLexer.flex


/* --------------------------Usercode Section------------------------ */

package dev.webfx.platform.ast.xml.parser.jflex;

import java_cup.runtime.*;
import        dev.webfx.platform.ast.xml.parser.javacup.XmlSymbols;
import static dev.webfx.platform.ast.xml.parser.javacup.XmlSymbols.*;
import        dev.webfx.platform.util.Numbers;


@SuppressWarnings("fallthrough")
public class XmlLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING_SINGLE_QUOTE = 2;
  public static final int STRING_DOUBLE_QUOTE = 4;
  public static final int STRING_GRAVE_ACCENT = 6;
  public static final int TEXT_CONTENT = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\3\0\1\10\1\11\3\0\1\12\1\0"+
    "\1\13\1\14\1\15\1\16\11\17\1\0\1\20\1\21"+
    "\1\22\1\23\2\0\4\24\1\25\1\24\24\26\1\0"+
    "\1\27\2\0\1\26\1\30\1\31\1\32\2\24\1\33"+
    "\1\34\1\35\4\26\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\5\26\12\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\2\2\1\3\1\4\1\5\2\1\2\6"+
    "\1\7\1\10\1\11\1\12\1\13\3\12\1\14\2\15"+
    "\1\16\1\1\2\14\1\17\1\1\1\20\1\21\1\2"+
    "\1\22\1\21\2\0\1\23\3\12\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\24\4\0"+
    "\1\35\1\0\1\21\1\0\3\12\7\0\1\12\1\36"+
    "\1\37\3\0\1\40\1\41\2\0\1\42\1\0\1\43"+
    "\3\0\1\44\1\45\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\310\0\360"+
    "\0\310\0\310\0\310\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8"+
    "\0\310\0\310\0\u01e0\0\310\0\u0208\0\u0230\0\u0258\0\u0280"+
    "\0\310\0\u02a8\0\310\0\u02d0\0\u02f8\0\u0320\0\u0348\0\u0370"+
    "\0\u0398\0\u03c0\0\u03e8\0\310\0\u0168\0\u0410\0\u0438\0\310"+
    "\0\u0460\0\u0488\0\u04b0\0\310\0\310\0\310\0\310\0\310"+
    "\0\310\0\310\0\310\0\310\0\u04d8\0\u0500\0\u0528\0\u0550"+
    "\0\u0578\0\310\0\u05a0\0\u05a0\0\u05c8\0\u05f0\0\u0618\0\u0640"+
    "\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730\0\u0758\0\u0780"+
    "\0\u01e0\0\u01e0\0\u07a8\0\u07d0\0\u07f8\0\310\0\310\0\u0820"+
    "\0\u0848\0\u01e0\0\u0870\0\310\0\u0898\0\u08c0\0\u08e8\0\310"+
    "\0\310\0\310";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\2\7\1\6\1\7\1\10\1\6\1\11\1\6"+
    "\1\12\1\6\1\13\1\14\1\15\1\16\1\17\1\6"+
    "\1\20\1\21\1\22\3\23\1\6\1\24\3\23\1\25"+
    "\3\23\1\26\5\23\1\27\1\23\2\30\1\31\2\30"+
    "\1\32\3\30\1\33\15\30\1\34\20\30\2\35\1\31"+
    "\2\35\1\32\1\35\1\33\17\35\1\34\20\35\2\36"+
    "\1\31\2\36\1\32\21\36\1\34\1\33\17\36\10\37"+
    "\1\40\10\37\1\41\26\37\52\0\1\7\63\0\2\42"+
    "\45\0\1\43\5\0\1\44\40\0\1\42\1\0\2\45"+
    "\5\0\1\46\5\0\1\46\30\0\1\42\1\0\2\17"+
    "\5\0\1\46\5\0\1\46\22\0\1\47\6\0\1\50"+
    "\50\0\2\23\4\0\3\23\2\0\17\23\16\0\2\23"+
    "\4\0\3\23\2\0\1\51\16\23\16\0\2\23\4\0"+
    "\3\23\2\0\16\23\1\52\16\0\2\23\4\0\3\23"+
    "\2\0\13\23\1\53\3\23\2\30\1\0\2\30\1\0"+
    "\3\30\1\0\15\30\1\0\20\30\2\0\1\31\45\0"+
    "\2\54\4\0\1\54\1\55\5\54\1\56\11\54\1\57"+
    "\2\54\1\60\1\54\1\61\3\54\1\62\3\54\1\63"+
    "\1\54\1\64\1\65\2\35\1\0\2\35\1\0\1\35"+
    "\1\0\17\35\1\0\20\35\2\36\1\0\2\36\1\0"+
    "\21\36\2\0\17\36\10\37\1\0\10\37\1\0\26\37"+
    "\31\0\1\66\3\0\1\67\1\70\4\0\1\71\21\0"+
    "\1\72\50\0\2\42\5\0\1\46\5\0\1\46\14\0"+
    "\2\43\1\7\2\43\1\10\42\43\12\0\2\73\2\0"+
    "\2\74\43\0\1\75\52\0\2\23\4\0\3\23\2\0"+
    "\5\23\1\76\11\23\16\0\2\23\4\0\3\23\2\0"+
    "\5\23\1\77\11\23\16\0\2\23\4\0\3\23\2\0"+
    "\16\23\1\100\16\0\2\101\4\0\2\101\3\0\4\101"+
    "\52\0\1\102\2\0\1\103\53\0\1\104\47\0\1\105"+
    "\50\0\1\106\16\0\2\74\43\0\1\107\52\0\2\23"+
    "\4\0\3\23\2\0\14\23\1\110\2\23\16\0\2\23"+
    "\4\0\3\23\2\0\5\23\1\111\11\23\16\0\2\23"+
    "\4\0\3\23\2\0\2\23\1\112\14\23\16\0\2\113"+
    "\4\0\2\113\3\0\4\113\55\0\1\114\46\0\1\115"+
    "\26\0\1\116\47\0\1\117\70\0\1\120\6\0\13\107"+
    "\1\121\34\107\16\0\2\23\4\0\3\23\2\0\2\23"+
    "\1\122\14\23\16\0\2\123\4\0\2\123\3\0\4\123"+
    "\33\0\1\124\74\0\1\125\50\0\1\126\1\0\13\107"+
    "\1\127\34\107\16\0\2\130\4\0\2\130\3\0\4\130"+
    "\33\0\1\131\47\0\1\132\27\0\13\107\1\127\7\107"+
    "\1\7\24\107";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2320];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\2\11\1\1\3\11\5\1\2\11\1\1\1\11"+
    "\4\1\1\11\1\1\1\11\10\1\1\11\1\1\2\0"+
    "\1\11\3\1\11\11\1\1\4\0\1\11\1\0\1\1"+
    "\1\0\3\1\7\0\3\1\3\0\2\11\2\0\1\1"+
    "\1\0\1\11\3\0\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuilder string = new StringBuilder();
    StringBuilder text = new StringBuilder();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public XmlLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(XmlSymbols.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <"+yytext()+">");
            }
          // fall through
          case 39: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 40: break;
          case 3:
            { yybegin(STRING_DOUBLE_QUOTE); string.setLength(0);
            }
          // fall through
          case 41: break;
          case 4:
            { yybegin(STRING_SINGLE_QUOTE); string.setLength(0);
            }
          // fall through
          case 42: break;
          case 5:
            { return symbol(MINUS);
            }
          // fall through
          case 43: break;
          case 6:
            { return symbol(NUMBER, Numbers.parseShortestNumber(yytext()));
            }
          // fall through
          case 44: break;
          case 7:
            { return symbol(LTAG);
            }
          // fall through
          case 45: break;
          case 8:
            { return symbol(EQUALS);
            }
          // fall through
          case 46: break;
          case 9:
            { yybegin(TEXT_CONTENT); text.setLength(0); return symbol(RTAG);
            }
          // fall through
          case 47: break;
          case 10:
            { return symbol(IDENTIFIER, yytext());
            }
          // fall through
          case 48: break;
          case 11:
            { yybegin(STRING_GRAVE_ACCENT); string.setLength(0);
            }
          // fall through
          case 49: break;
          case 12:
            { string.append( yytext() );
            }
          // fall through
          case 50: break;
          case 13:
            { throw new RuntimeException("Unterminated string at end of line");
            }
          // fall through
          case 51: break;
          case 14:
            { yybegin(YYINITIAL); return symbol(STRING, string.toString());
            }
          // fall through
          case 52: break;
          case 15:
            { text.append(yytext());
            }
          // fall through
          case 53: break;
          case 16:
            { if (text.length() > 0) {
                                         String textContent = text.toString().trim();
                                         if (!textContent.isEmpty()) {
                                             yypushback(1); // Push back the '<' character
                                             return symbol(TEXT, textContent);
                                         }
                                     }
                                     yybegin(YYINITIAL);
                                     return symbol(LTAG);
            }
          // fall through
          case 54: break;
          case 17:
            { return symbol(NUMBER, Double.valueOf(yytext()));
            }
          // fall through
          case 55: break;
          case 18:
            { return symbol(RTAGSLASH);
            }
          // fall through
          case 56: break;
          case 19:
            { return symbol(LTAGSLASH);
            }
          // fall through
          case 57: break;
          case 20:
            { string.append( yytext().substring(1) );
            }
          // fall through
          case 58: break;
          case 21:
            { string.append( '\"' );
            }
          // fall through
          case 59: break;
          case 22:
            { string.append( '/' );
            }
          // fall through
          case 60: break;
          case 23:
            { string.append( '\\' );
            }
          // fall through
          case 61: break;
          case 24:
            { string.append( '\b' );
            }
          // fall through
          case 62: break;
          case 25:
            { string.append( '\f' );
            }
          // fall through
          case 63: break;
          case 26:
            { string.append( '\n' );
            }
          // fall through
          case 64: break;
          case 27:
            { string.append( '\r' );
            }
          // fall through
          case 65: break;
          case 28:
            { string.append( '\t' );
            }
          // fall through
          case 66: break;
          case 29:
            { if (text.length() > 0) {
                                         String textContent = text.toString().trim();
                                         if (!textContent.isEmpty()) {
                                             yypushback(2); // Push back the '</' characters
                                             return symbol(TEXT, textContent);
                                         }
                                     }
                                     yybegin(YYINITIAL);
                                     return symbol(LTAGSLASH);
            }
          // fall through
          case 67: break;
          case 30:
            { return symbol(NULL);
            }
          // fall through
          case 68: break;
          case 31:
            { return symbol(BOOLEAN, Boolean.TRUE);
            }
          // fall through
          case 69: break;
          case 32:
            { text.append(">");
            }
          // fall through
          case 70: break;
          case 33:
            { text.append("<");
            }
          // fall through
          case 71: break;
          case 34:
            { return symbol(BOOLEAN, Boolean.FALSE);
            }
          // fall through
          case 72: break;
          case 35:
            { text.append("&");
            }
          // fall through
          case 73: break;
          case 36:
            { String hex = yytext().substring(2); 
                                   int code = Integer.parseInt(hex, 16);
                                   string.append((char) code);
            }
          // fall through
          case 74: break;
          case 37:
            { text.append("'");
            }
          // fall through
          case 75: break;
          case 38:
            { text.append("\"");
            }
          // fall through
          case 76: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
