
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package dev.webfx.platform.ast.toml.parser.javacup;

/** CUP generated interface containing symbol constants. */
public interface TomlSymbols {
  /* terminals */
  public static final int DATETIME = 13;
  public static final int INTEGER = 8;
  public static final int TIME = 15;
  public static final int DATE = 14;
  public static final int BOOLEAN = 10;
  public static final int NULL = 7;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int DOT = 4;
  public static final int RBRACK = 3;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int IDENTIFIER = 12;
  public static final int LBRACK = 2;
  public static final int EQUALS = 6;
  public static final int FLOAT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACK",
  "RBRACK",
  "DOT",
  "COMMA",
  "EQUALS",
  "NULL",
  "INTEGER",
  "FLOAT",
  "BOOLEAN",
  "STRING",
  "IDENTIFIER",
  "DATETIME",
  "DATE",
  "TIME"
  };
}

