
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package dev.webfx.platform.ast.xml.parser.javacup;

import dev.webfx.platform.ast.AST;
import dev.webfx.platform.ast.AstArray;
import dev.webfx.platform.ast.AstObject;
import dev.webfx.platform.ast.ReadOnlyAstArray;
import dev.webfx.platform.util.Numbers;
import dev.webfx.platform.util.tuples.Pair;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class JavaCupXmlParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return XmlSymbols.class;
}

  /** Default constructor. */
  @Deprecated
  public JavaCupXmlParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public JavaCupXmlParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public JavaCupXmlParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\020\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\003\003\000\002\003\004\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\004\012\000\002\004\011\000\002\004\006\000\002" +
    "\007\003\000\002\006\004\000\002\006\002\000\002\005" +
    "\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\035\000\020\004\013\011\007\012\005\013\004\014" +
    "\006\015\010\017\014\001\002\000\004\012\037\001\002" +
    "\000\006\002\ufffe\006\ufffe\001\002\000\006\002\ufffb\006" +
    "\ufffb\001\002\000\006\002\ufffa\006\ufffa\001\002\000\006" +
    "\002\ufffc\006\ufffc\001\002\000\004\002\036\001\002\000" +
    "\006\002\uffff\006\uffff\001\002\000\004\016\016\001\002" +
    "\000\006\002\ufff9\006\ufff9\001\002\000\006\002\000\006" +
    "\000\001\002\000\010\005\ufff5\007\ufff5\016\ufff5\001\002" +
    "\000\010\005\ufff3\007\ufff3\016\ufff3\001\002\000\010\005" +
    "\021\007\024\016\023\001\002\000\022\004\013\006\030" +
    "\011\007\012\005\013\004\014\006\015\010\017\014\001" +
    "\002\000\010\005\ufff4\007\ufff4\016\ufff4\001\002\000\004" +
    "\010\025\001\002\000\006\002\ufff6\006\ufff6\001\002\000" +
    "\004\015\026\001\002\000\010\005\ufff2\007\ufff2\016\ufff2" +
    "\001\002\000\004\006\033\001\002\000\004\016\016\001" +
    "\002\000\004\005\032\001\002\000\006\002\ufff7\006\ufff7" +
    "\001\002\000\004\016\016\001\002\000\004\005\035\001" +
    "\002\000\006\002\ufff8\006\ufff8\001\002\000\004\002\001" +
    "\001\002\000\006\002\ufffd\006\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\035\000\010\002\010\003\011\004\014\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\006\017\001\001\000" +
    "\004\005\021\001\001\000\010\002\026\003\011\004\014" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\030\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\033\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$JavaCupXmlParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$JavaCupXmlParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$JavaCupXmlParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    /* Change the method report_error so it will display the line and
       column of where the error occurred in the input as well as the
       reason for the error which is passed into the method in the
       String 'message'. */
    public void report_error(String message, Object info) {
        System.err.println(generateErrorMessage(message, info));
    }
   
    /* Change the method report_fatal_error so when it reports a fatal
       error it will display the line and column number of where the
       fatal error occurred in the input as well as the reason for the
       fatal error which is passed into the method in the object
       'message' and then exit.*/
    public void report_fatal_error(String message, Object info) {
        throw new IllegalArgumentException(generateErrorMessage(message, info));
    }

    private String generateErrorMessage(String message, Object info) {

        /* Create a StringBuilder called 'm' with the string 'Error' in it. */
        StringBuilder m = new StringBuilder("Error");

        /* Check if the information passed to the method is the same
           type as the type java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the
               information in the object info that is being typecasted
               as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);

            /* Check if the line number in the input is greater or
               equal to zero. */
            if (s.left >= 0) {
                /* Add to the end of the StringBuilder error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)
                    /* Add to the end of the StringBuilder error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }

        /* Add to the end of the StringBuilder error message created in
           this method the message that was passed into this method. */
        m.append(" : "+message);

        return m.toString();
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$JavaCupXmlParser$actions {
  private final JavaCupXmlParser parser;

  /** Constructor */
  CUP$JavaCupXmlParser$actions(JavaCupXmlParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$JavaCupXmlParser$do_action_part00000000(
    int                        CUP$JavaCupXmlParser$act_num,
    java_cup.runtime.lr_parser CUP$JavaCupXmlParser$parser,
    java.util.Stack            CUP$JavaCupXmlParser$stack,
    int                        CUP$JavaCupXmlParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$JavaCupXmlParser$result;

      /* select the action based on the action number */
      switch (CUP$JavaCupXmlParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= xml_element EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).value;
		RESULT = start_val;
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$JavaCupXmlParser$parser.done_parsing();
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // xml_element ::= xml_object 
            {
              Object RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		AstObject o = (AstObject)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = o; 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_element",0, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // xml_element ::= xml_scalar 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = s; 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_element",0, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // xml_scalar ::= NUMBER 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = n; 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_scalar",1, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // xml_scalar ::= MINUS NUMBER 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = Numbers.negate(n); 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_scalar",1, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // xml_scalar ::= STRING 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = s; 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_scalar",1, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // xml_scalar ::= BOOLEAN 
            {
              Object RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		Boolean b = (Boolean)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = b; 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_scalar",1, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // xml_scalar ::= NULL 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_scalar",1, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // xml_scalar ::= TEXT 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = t; 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_scalar",1, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // xml_object ::= LTAG xml_tag_name xml_attributes RTAG xml_element LTAGSLASH xml_tag_name RTAG 
            {
              AstObject RESULT =null;
		int tagleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-6)).left;
		int tagright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-6)).right;
		String tag = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-6)).value;
		int attrsleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-5)).left;
		int attrsright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-5)).right;
		AstObject attrs = (AstObject)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-5)).value;
		int contentleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-3)).left;
		int contentright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-3)).right;
		Object content = (Object)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-3)).value;
		int endTagleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).left;
		int endTagright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).right;
		String endTag = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).value;
		 
                  if (!tag.equals(endTag))
                      throw new IllegalArgumentException("Mismatched XML tags: " + tag + " and " + endTag);

                  AstObject result;
                  if (content instanceof AstObject) {
                      // If content is an object, merge it with attributes
                      result = attrs;
                      AstObject contentObj = (AstObject) content;
                      ReadOnlyAstArray keys = contentObj.keys();
                      for (int i = 0, size = keys.size(); i < size; i++) {
                          String key = keys.getString(i);
                          result.set(key, (Object) contentObj.get(key));
                      }
                  } else if (content != null) {
                      // If content is a scalar value, add it with special key
                      result = attrs.set("value", content);
                  } else {
                      // No content, just return attributes
                      result = attrs;
                  }

                  // Create a new object with the tag name as the key and the result as the value
                  RESULT = AST.createObject().set(tag, result);
               
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_object",2, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-7)), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // xml_object ::= LTAG xml_tag_name xml_attributes RTAG LTAGSLASH xml_tag_name RTAG 
            {
              AstObject RESULT =null;
		int tagleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-5)).left;
		int tagright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-5)).right;
		String tag = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-5)).value;
		int attrsleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-4)).left;
		int attrsright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-4)).right;
		AstObject attrs = (AstObject)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-4)).value;
		int endTagleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).left;
		int endTagright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).right;
		String endTag = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).value;
		 
                  if (!tag.equals(endTag))
                      throw new IllegalArgumentException("Mismatched XML tags: " + tag + " and " + endTag);

                  // Empty tag with attributes
                  RESULT = AST.createObject().set(tag, attrs);
               
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_object",2, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-6)), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // xml_object ::= LTAG xml_tag_name xml_attributes RTAGSLASH 
            {
              AstObject RESULT =null;
		int tagleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-2)).left;
		int tagright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-2)).right;
		String tag = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-2)).value;
		int attrsleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).left;
		int attrsright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).right;
		AstObject attrs = (AstObject)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).value;
		 
                  // Self-closing tag, create an object with the tag name as the key
                  RESULT = AST.createObject().set(tag, attrs);
               
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_object",2, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-3)), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // xml_tag_name ::= IDENTIFIER 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = id; 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_tag_name",5, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // xml_attributes ::= xml_attributes xml_attribute 
            {
              AstObject RESULT =null;
		int attrsleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).left;
		int attrsright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).right;
		AstObject attrs = (AstObject)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)).value;
		int attrleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		Pair<String,Object> attr = (Pair<String,Object>)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = attrs.set(attr.get1(), attr.get2()); 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_attributes",4, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-1)), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // xml_attributes ::= 
            {
              AstObject RESULT =null;
		 RESULT = AST.createObject(); 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_attributes",4, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // xml_attribute ::= IDENTIFIER EQUALS STRING 
            {
              Pair<String,Object> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$JavaCupXmlParser$stack.peek()).value;
		 RESULT = new Pair(id, value); 
              CUP$JavaCupXmlParser$result = parser.getSymbolFactory().newSymbol("xml_attribute",3, ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.elementAt(CUP$JavaCupXmlParser$top-2)), ((java_cup.runtime.Symbol)CUP$JavaCupXmlParser$stack.peek()), RESULT);
            }
          return CUP$JavaCupXmlParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$JavaCupXmlParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$JavaCupXmlParser$do_action(
    int                        CUP$JavaCupXmlParser$act_num,
    java_cup.runtime.lr_parser CUP$JavaCupXmlParser$parser,
    java.util.Stack            CUP$JavaCupXmlParser$stack,
    int                        CUP$JavaCupXmlParser$top)
    throws java.lang.Exception
    {
              return CUP$JavaCupXmlParser$do_action_part00000000(
                               CUP$JavaCupXmlParser$act_num,
                               CUP$JavaCupXmlParser$parser,
                               CUP$JavaCupXmlParser$stack,
                               CUP$JavaCupXmlParser$top);
    }
}

}
