
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package dev.webfx.platform.ast.xml.parser.javacup;

/** CUP generated interface containing symbol constants. */
public interface XmlSymbols {
  /* terminals */
  public static final int MINUS = 9;
  public static final int RTAG = 3;
  public static final int NUMBER = 8;
  public static final int BOOLEAN = 10;
  public static final int NULL = 7;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int RTAGSLASH = 5;
  public static final int error = 1;
  public static final int LTAG = 2;
  public static final int IDENTIFIER = 12;
  public static final int TEXT = 13;
  public static final int EQUALS = 6;
  public static final int LTAGSLASH = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LTAG",
  "RTAG",
  "LTAGSLASH",
  "RTAGSLASH",
  "EQUALS",
  "NULL",
  "NUMBER",
  "MINUS",
  "BOOLEAN",
  "STRING",
  "IDENTIFIER",
  "TEXT"
  };
}

