// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/dev/webfx/platform/ast/toml/parser/jflex/TomlLexer.flex

/* --------------------------Usercode Section------------------------ */

package dev.webfx.platform.ast.toml.parser.jflex;

import java_cup.runtime.*;
import        dev.webfx.platform.ast.toml.parser.javacup.TomlSymbols;
import static dev.webfx.platform.ast.toml.parser.javacup.TomlSymbols.*;
import        dev.webfx.platform.util.Numbers;


@SuppressWarnings("fallthrough")
public class TomlLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\1\5\3\0\1\6\3\0\1\7\1\10"+
    "\1\11\1\12\1\0\1\13\1\14\6\15\2\16\1\17"+
    "\2\0\1\20\3\0\4\21\1\22\1\21\15\23\1\24"+
    "\5\23\1\25\1\26\1\27\1\30\1\0\1\23\1\0"+
    "\1\31\1\32\2\21\1\33\1\34\5\23\1\35\1\23"+
    "\1\36\1\37\2\23\1\40\1\41\1\42\1\43\2\23"+
    "\1\44\2\23\u0185\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\2\1\1\1\3\1\4"+
    "\2\5\1\6\1\7\1\10\1\11\3\7\1\0\1\12"+
    "\2\0\1\12\1\0\1\5\4\0\3\7\1\12\2\0"+
    "\2\13\1\5\2\0\2\13\3\5\3\7\5\0\1\5"+
    "\4\0\1\5\1\7\1\14\1\15\2\0\3\13\1\0"+
    "\1\5\1\0\3\13\1\5\1\16\1\17\1\13\2\0"+
    "\1\13\3\0\1\20\2\0\1\21\1\20\10\0\1\22"+
    "\2\0\1\22\1\0\1\22\3\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\45\0\112\0\157\0\224\0\271\0\45"+
    "\0\45\0\336\0\u0103\0\45\0\u0128\0\45\0\45\0\u014d"+
    "\0\u0172\0\u0197\0\u01bc\0\u01e1\0\u0206\0\u022b\0\u0250\0\u0275"+
    "\0\u029a\0\u02bf\0\u02e4\0\u0309\0\u032e\0\u0353\0\u0378\0\u039d"+
    "\0\45\0\u03c2\0\u03e7\0\u040c\0\u0431\0\u0456\0\u047b\0\u04a0"+
    "\0\u04c5\0\u04ea\0\u050f\0\u0534\0\u0559\0\u057e\0\u05a3\0\u05c8"+
    "\0\u05ed\0\u0612\0\u0637\0\u065c\0\u0681\0\u06a6\0\u06cb\0\u06f0"+
    "\0\u0715\0\u073a\0\u075f\0\u0784\0\u0128\0\u0128\0\u07a9\0\u07ce"+
    "\0\u07f3\0\u0818\0\u083d\0\u0862\0\u0887\0\u08ac\0\u06f0\0\u0715"+
    "\0\u073a\0\u08d1\0\u0128\0\45\0\u08f6\0\u091b\0\u0940\0\u0965"+
    "\0\u098a\0\u09af\0\u09d4\0\u09f9\0\u0a1e\0\u0a43\0\u0a68\0\u0a43"+
    "\0\u0a8d\0\u0ab2\0\u0ad7\0\u0afc\0\u0b21\0\u0b46\0\u0b6b\0\u0b90"+
    "\0\u0bb5\0\u0bda\0\u0bff\0\45\0\u0c24\0\u0c49\0\u0c6e\0\u0c93"+
    "\0\u0cb8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\2\1\10"+
    "\1\2\1\11\1\12\3\13\1\2\1\14\5\15\1\16"+
    "\1\2\1\17\3\15\1\20\1\15\1\21\3\15\1\22"+
    "\2\15\47\0\1\3\42\0\2\23\2\0\1\24\22\23"+
    "\1\25\15\23\2\6\1\3\1\4\41\6\6\26\1\27"+
    "\36\26\12\0\1\30\4\31\3\0\1\32\7\0\1\33"+
    "\1\32\3\0\1\34\4\0\1\35\12\0\1\30\4\31"+
    "\3\0\1\32\10\0\1\32\22\0\1\15\1\0\4\15"+
    "\2\0\5\15\3\0\14\15\11\0\1\15\1\0\4\15"+
    "\2\0\5\15\3\0\1\36\13\15\11\0\1\15\1\0"+
    "\4\15\2\0\5\15\3\0\12\15\1\37\1\15\11\0"+
    "\1\15\1\0\4\15\2\0\5\15\3\0\7\15\1\40"+
    "\4\15\2\23\2\0\1\41\22\23\1\25\15\23\4\0"+
    "\1\42\40\0\2\23\2\0\41\23\6\26\1\41\36\26"+
    "\6\0\1\43\51\0\1\44\3\45\40\0\1\30\4\46"+
    "\1\47\2\0\1\32\10\0\1\32\20\0\1\50\1\0"+
    "\1\50\1\0\1\51\3\52\41\0\2\53\43\0\3\54"+
    "\42\0\4\55\2\0\2\55\6\0\4\55\21\0\1\15"+
    "\1\0\4\15\2\0\5\15\3\0\4\15\1\56\7\15"+
    "\11\0\1\15\1\0\4\15\2\0\5\15\3\0\4\15"+
    "\1\57\7\15\11\0\1\15\1\0\4\15\2\0\5\15"+
    "\3\0\12\15\1\60\1\15\4\42\1\61\40\42\6\43"+
    "\1\62\36\43\13\0\4\45\3\0\1\32\7\0\1\63"+
    "\1\32\3\0\1\64\4\0\1\65\13\0\4\45\3\0"+
    "\1\32\10\0\1\32\23\0\1\30\4\66\3\0\1\32"+
    "\10\0\1\32\24\0\4\67\41\0\1\51\3\52\41\0"+
    "\4\52\13\0\1\70\4\0\1\71\4\0\1\72\13\0"+
    "\4\52\40\0\1\30\2\53\5\0\1\32\10\0\1\32"+
    "\23\0\1\30\3\54\4\0\1\32\10\0\1\32\23\0"+
    "\1\30\4\55\2\0\1\55\1\73\6\0\2\55\1\73"+
    "\1\55\21\0\1\15\1\0\4\15\2\0\5\15\3\0"+
    "\10\15\1\74\3\15\11\0\1\15\1\0\4\15\2\0"+
    "\5\15\3\0\4\15\1\75\7\15\11\0\1\15\1\0"+
    "\4\15\2\0\5\15\3\0\2\15\1\76\11\15\4\42"+
    "\1\77\40\42\6\43\1\100\36\43\13\0\2\101\43\0"+
    "\3\102\42\0\4\103\2\0\2\103\6\0\4\103\21\0"+
    "\1\104\1\30\4\105\3\0\1\32\10\0\1\32\24\0"+
    "\4\106\41\0\2\107\43\0\3\110\42\0\4\111\2\0"+
    "\2\111\6\0\4\111\17\0\1\50\1\0\1\50\1\30"+
    "\1\112\3\55\2\0\1\55\1\73\6\0\2\55\1\73"+
    "\1\55\21\0\1\15\1\0\4\15\2\0\5\15\3\0"+
    "\2\15\1\113\11\15\4\42\1\114\40\42\6\43\1\114"+
    "\36\43\13\0\2\101\5\0\1\32\10\0\1\32\24\0"+
    "\3\102\4\0\1\32\10\0\1\32\24\0\4\103\2\0"+
    "\1\103\1\115\6\0\2\103\1\115\1\103\23\0\4\116"+
    "\40\0\1\30\4\105\3\0\1\32\10\0\1\32\30\0"+
    "\1\117\37\0\1\30\4\55\2\0\1\55\1\73\6\0"+
    "\2\55\1\73\1\55\2\0\1\71\4\0\1\72\7\0"+
    "\1\50\1\0\1\50\1\0\1\120\3\103\2\0\1\103"+
    "\1\115\6\0\2\103\1\115\1\103\23\0\4\121\41\0"+
    "\4\122\41\0\4\103\2\0\1\103\1\115\6\0\2\103"+
    "\1\115\1\103\2\0\1\71\4\0\1\72\11\0\1\123"+
    "\46\0\4\124\41\0\4\125\40\0\1\126\45\0\4\127"+
    "\41\0\4\130\52\0\1\131\33\0\4\132\41\0\4\133"+
    "\45\0\1\134\40\0\4\135\41\0\4\136\45\0\1\137"+
    "\40\0\4\140\41\0\4\141\35\0\1\142\1\0\1\142"+
    "\1\143\12\0\1\144\32\0\4\145\41\0\4\146\41\0"+
    "\4\147\35\0\1\142\1\0\1\142\1\0\4\146\6\0"+
    "\1\144\36\0\1\150\40\0\4\151\41\0\4\144\26\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3293];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\2\11\2\1\1\11\1\1\2\11"+
    "\3\1\1\0\1\1\2\0\1\1\1\0\1\1\4\0"+
    "\3\1\1\11\2\0\3\1\2\0\10\1\5\0\1\1"+
    "\4\0\4\1\2\0\3\1\1\0\1\1\1\0\5\1"+
    "\1\11\1\1\2\0\1\1\3\0\1\1\2\0\2\1"+
    "\10\0\1\1\2\0\1\11\1\0\1\1\3\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuilder string = new StringBuilder();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public TomlLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(TomlSymbols.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <"+yytext()+">");
            }
          // fall through
          case 19: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 20: break;
          case 3:
            { return symbol(COMMA);
            }
          // fall through
          case 21: break;
          case 4:
            { return symbol(DOT);
            }
          // fall through
          case 22: break;
          case 5:
            { return symbol(INTEGER, Numbers.parseShortestNumber(yytext()));
            }
          // fall through
          case 23: break;
          case 6:
            { return symbol(EQUALS);
            }
          // fall through
          case 24: break;
          case 7:
            { return symbol(IDENTIFIER, yytext());
            }
          // fall through
          case 25: break;
          case 8:
            { return symbol(LBRACK);
            }
          // fall through
          case 26: break;
          case 9:
            { return symbol(RBRACK);
            }
          // fall through
          case 27: break;
          case 10:
            { String text = yytext();
                                   return symbol(STRING, text.substring(1, text.length() - 1));
            }
          // fall through
          case 28: break;
          case 11:
            { return symbol(FLOAT, Double.valueOf(yytext()));
            }
          // fall through
          case 29: break;
          case 12:
            { return symbol(NULL);
            }
          // fall through
          case 30: break;
          case 13:
            { return symbol(BOOLEAN, Boolean.TRUE);
            }
          // fall through
          case 31: break;
          case 14:
            { return symbol(BOOLEAN, Boolean.FALSE);
            }
          // fall through
          case 32: break;
          case 15:
            { String text = yytext();
                                   return symbol(STRING, text.substring(3, text.length() - 3));
            }
          // fall through
          case 33: break;
          case 16:
            { return symbol(TIME, yytext());
            }
          // fall through
          case 34: break;
          case 17:
            { return symbol(DATE, yytext());
            }
          // fall through
          case 35: break;
          case 18:
            { return symbol(DATETIME, yytext());
            }
          // fall through
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
